### Send a DELETE with full HTTP Request Spec
DELETE  https://localhost:7102/catalog/3 HTTP/1.1

### GET token from Auth0
curl --request POST \
  --url https://dev-1ydn98uq.us.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"jEv3BD1gJhCaLrMRr9nqizUISQE6TwhN","client_secret":"OqQqCbCMmtT7ZmF0EaDLaDtZ1xBgnnQgLhM7d41Y4VhUc4TS0pvOENN99l9dYV47","audience":"https://uncanny-violin-2","grant_type":"client_credentials"}'

### DELETE a Item to the Catalog collection
curl --request DELETE \
    --url https://localhost:7102/catalog/3 \
    --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IndLVUxXNFlkVThGYldzcVdndF9hbiJ9.eyJpc3MiOiJodHRwczovL2Rldi0xeWRuOTh1cS51cy5hdXRoMC5jb20vIiwic3ViIjoiakV2M0JEMWdKaENhTHJNUnI5bnFpelVJU1FFNlR3aE5AY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vdW5jYW5ueS12aW9saW4tMiIsImlhdCI6MTY1MTI3MzMyMCwiZXhwIjoxNjUxMzU5NzIwLCJhenAiOiJqRXYzQkQxZ0poQ2FMck1ScjlucWl6VUlTUUU2VHdoTiIsInNjb3BlIjoiZGVsZXRlOmNhdGFsb2ciLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.RDsV-jAtKQ213gUQJCRDgXBdtQ5GWPUq8MfyftfpjdMJLY62AZrPSAC3qpwHNVkUKC0QOHypc1zHayaupBW2KCmxnXR5PBtZez2B56S-QsNqPjpa7nzinFu1G4kpGh8yLf9oOc-956ofIgUbz7c-fXIXAHaMz7j_z3ZO5GovVFywuN28wLK796i8KEupYRUW_akkgu_RagjVccWEPHEnn4lnMOBCHf5KXDpTclA6pwauoRVqEe6YdhfqnwHrlaec4XCGYSJQeZ_WuVOJsjIy608MqKiG2TsW9OeGg-SmGwZEVjZJTmKRlj615Rm0wsk7nw8i6AzWg1gX-GdVYzTkMg'