### Send a DELETE with full HTTP Request Spec
DELETE  https://localhost:7102/catalog/3 HTTP/1.1

### GET token from Auth0
curl --request POST \
  --url https://dev-1ydn98uq.us.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"C5sehVi5o5H64CeByW8V9Ptg2wQck9l3","client_secret":"6mAHlnrmO3fCpp3mKgncrOGUfkeNzb6vSKC6uBKjPiN_-XYxq161qT08mHVpWRx9","audience":"https://uncanny-violin","grant_type":"client_credentials"}'

### DELETE a Item to the Catalog collection
curl --request DELETE \
    --url https://localhost:7102/catalog/3 \
    --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IndLVUxXNFlkVThGYldzcVdndF9hbiJ9.eyJpc3MiOiJodHRwczovL2Rldi0xeWRuOTh1cS51cy5hdXRoMC5jb20vIiwic3ViIjoiQzVzZWhWaTVvNUg2NENlQnlXOFY5UHRnMndRY2s5bDNAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vdW5jYW5ueS12aW9saW4iLCJpYXQiOjE2NTExNjc4MTcsImV4cCI6MTY1MTI1NDIxNywiYXpwIjoiQzVzZWhWaTVvNUg2NENlQnlXOFY5UHRnMndRY2s5bDMiLCJzY29wZSI6ImRlbGV0ZTpjYXRhbG9nIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.pkNfjk7K_NMZwIKv8O__ZvzsMHg_9tPkLDEfjAhZLoKP_J214CfKvwmyJsjFrz_WCIUdbBfkEnV1p9VwaMTzuhjJWiHbYDsTpYSCxmULx-ZfxA1cFfz4zNc3wnGzsgzwZ3GNhD9CrsNhvvfM-Bu-uJbZSqKwDyhL97cbHXBLotYIxZVkUnMRoISvKC__-5dZa5banusbPc7z_Yalv2endSyzLMAEzc7dzBELgmoDlykbxXBR2m3zo3CuclaA1GdeaxqmXOp0mlQZFPB5BZjU1gi7gYczsmFpb9RNGwWA7uIT-M663_NS_OYII3Y3IOO2rd_4cqwtTp2TbdGKQ53vAQ'