### GET token from Auth0
curl --request POST \
  --url https://dev-1ydn98uq.us.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"tgjeVxEVYQCKfzsHP41pa0io9OnlLqRt","client_secret":"hl8q35BME-bgVZvNHp5-B9JYR-4gLW6q6OdprQp-3mDVAGChrPkVRQjcukGl-Pi7","audience":"https://uncanny-violin","grant_type":"client_credentials"}'

### DELETE a Item to the Catalog collection
curl --request DELETE \ 
    --url https://localhost:7102/catalog/3 \
    --header 'authorization: Bearer {eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IndLVUxXNFlkVThGYldzcVdndF9hbiJ9.eyJpc3MiOiJodHRwczovL2Rldi0xeWRuOTh1cS51cy5hdXRoMC5jb20vIiwic3ViIjoidGdqZVZ4RVZZUUNLZnpzSFA0MXBhMGlvOU9ubExxUnRAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vdW5jYW5ueS12aW9saW4iLCJpYXQiOjE2NTExMDg5NjAsImV4cCI6MTY1MTE5NTM2MCwiYXpwIjoidGdqZVZ4RVZZUUNLZnpzSFA0MXBhMGlvOU9ubExxUnQiLCJzY29wZSI6ImRlbGV0ZTpjYXRhbG9nIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.msiXBw8LZZOC-1YQQ5xTYf2R31jTMdkglZjAGnoUwUxBJnn0CVs74ZYwABryA2XpVaDtXD05y6cj1ODh9rAc9KyQO9H9DlPvkN3-Cg1pxjeN-Iixvh3mv3MMyFZ69yiTFJoVSmQIB6BFffdDVAU3VC6fZsPnwRkm3TlUdnO4AJAhzaMnbKNLTK_VNoJqEKT0iGONV_U_LuT3HTpT89sXG6Jp5mHlSoiMlQkPyIJZBmImHUXnEN2DC7Rvwu6sygXjeJW_ZecDyLCeDFMgsYAV4QpOj_qMNSUj24WQQ8Vrpv2nPdtllrPZeqmLd6kX1j_44AO2mNIA91slvkKR9p7E3A}' 