### Send an implicit GET
https://localhost:5001


### Send and exlicit GET
GET https://localhost:7102 HTTP/1.1


### Send a POST with full HTTP Request Spec
POST https://localhost:7102 HTTP/1.1
content-type: application/json

{
    "name": "test",
    "time": "Sun, 27 F 2022 18:27:50 GMT"
}

### Send a PUT with full HTTP Request Spec
PUT https://localhost:5001 HTTP/1.1
content-type: application/json

{
    "name": "test",
    "time": "Sun, 27 F 2022 18:27:50 GMT"
}

### Send a PUT with full HTTP Request Spec
DELETE  https://localhost:7102/catalog/3 HTTP/1.1


### GET Catalog
https://localhost:7102/catalog


### Send a POST
POST https://localhost:7102/catalog HTTP/1.1
content-type: application/json

{
    "name" : "Shoes",
    "description": "Running Shoes",
    "brand": "Nike",
    "price": 109.99
}